### Creating Contact
POST http://localhost:8080/contacts
Content-Type: application/json

{
    "firstName": "Belinda",
    "lastName": "Milford",
    "email": "berlinda.milford@gmail.com",
    "favoriteColor": "Purple",
    "birthday": "09/22/1980"
}


### Getting all the contacts
GET http://localhost:8080/contacts


### Getting a single contact (the one I just created)
GET http://localhost:8080/contacts/68e1e4fa9e645f42f498ba73


### Updating the Contact's information (in this case the name)
PUT http://localhost:8080/contacts/68e1e4fa9e645f42f498ba73
Content-Type: application/json

{
    "firstName": "Berlinda",
    "lastName": "Milford",
    "email": "berlinda.milford@gmail.com",
    "favoriteColor": "Purple",
    "birthday": "09/22/1980"
}


### Deleting the contact I just created
DELETE http://localhost:8080/contacts/68e1e4fa9e645f42f498ba73